### ISSUE TITLE
Add content to README

### ISSUE THREAD

**Issue by BLelgemann** [MeikeRietz/Aufgabe-1#1]
Die README-Datei hat bisher noch keinen Inhalt. Hier wäre es schön, eine Übersicht zu bekommen, worum es in der Aufgabe geht und eventuell auch, wie der Status der Bearbeitung ist.

Viele Grüße
Britta

**Comment by MeikeRietz** [comment]
Hi Britta, 

guter Hinweis! Der Text ist jetzt fertig. :)

LG
Meike
