### ISSUE TITLE
Tippfehler Kapitel 4, Absatz 3

### ISSUE THREAD

**Issue by BLelgemann** [MeikeRietz/Aufgabe-1#3]
In Kapitel 4, Absatz 3, hat sich ein Tippfehler eingeschlichen: ". . . somit ein geziletes Suchen . . . ." Dies müsste korrigiert werden.

Viele Grüße
Britta

**Comment by MeikeRietz** [comment]
Danke Britta, der Fehler wurde korrigiert.

LG
Meike
